version: "3.6"

services:
  matthewvarga:
    build: "./matthewvarga.net/."
    ports:
      - "8080"

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www
    depends_on:
      - "matthewvarga"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www --email matthew.varga@mail.utoronto.ca --agree-tos --no-eff-email --force-renewal -d matthewvarga.net -d www.matthewvarga.net

volumes:
  certbot-etc:
  certbot-var:
  webroot: