version: "3.6"
services:
  matthewvarga.net:
    build: "./matthewvarga.net/."
    ports:
      - "8080"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "matthewvarga.net"